### ISSUE TITLE
Way to define complete docpad config.

### ISSUE THREAD

**Issue by mikeumus** [mikeumus/docpad-instance-spawn#1]
Upon executing `docpadSpawn(9967)`, output ends like so:

```
info: Welcome to DocPad v6.54.5 (global installation: /var/lib/stickshift/68ddb90b5961458485e48f57fc58bc92/app-root/data/346321/node_modules/docpad)
info: Contribute: http://docpad.org/docs/contribute
info: Plugins:
info: Environment: development
info: Generating...
notice: DocPad is currently running without any plugins installed. You probably want to install some: http://docpad.org/plugins
Error: Cannot generate website as the src dir was not found
    at /var/lib/stickshift/68ddb90b5961458485e48f57fc58bc92/app-root/data/346321/node_modules/docpad/out/lib/docpad.js:3103:21
    at /var/lib/stickshift/68ddb90b5961458485e48f57fc58bc92/app-root/data/346321/node_modules/docpad/node_modules/safefs/out/lib/safefs.js:186:18
    at Object.cb [as oncomplete] (fs.js:168:19)
```

A syntax error in a root `docpad.coffee` file will create a fatal error for the DocPad instance which means this file is being read. `srcPath` & `outPath` are defined in said `docpad.coffee` as "docpad/src" & "docpad/out" yet the above error is still produced. So the question is, how to get the DocPad instance to the src folder it wants?

**Comment by mikeumus** [comment]
Possibly as a argument linking to a docpad.coffee-like file or by allowing for a bracketed function argument for `docpadSpawn()` something like:

```
docpadSpawn(port, {
           configSetting: 1,
           configSetting: 2
}
```

However the docpadSpwan function is an express function simply to create a express server so sending the docpad.coffee config this way may not work as stated above.

**Comment by balupton** [comment]
You'll need to pass over the `rootPath` configuration variable

**Comment by mikeumus** [comment]
Thanks @balupton. 

I have `rootPath` set like the below and the error persists:

```
 # =================================
        # Paths Configuration

        # Root Path
        # The root path of our our project
        rootPath: 'docpad/'

        # Out Path
        # Where should we put our generated website files?
        # If it is a relative path, it will have the resolved `rootPath` prepended to it
        outPath: 'docpad/out'  # default

        # Src Path
        # Where can we find our source website files?
        # If it is a relative path, it will have the resolved `rootPath` prepended to it
        srcPath: 'docpad/src'  # default
```

I also tried `/docpad`.

**Comment by balupton** [comment]
Hrmm... Try with `rootPath` being an absolute path

**Comment by mikeumus** [comment]
Yeah it worked with `rootPath: process.cwd() + '/public/docpad'`. I've added this note to the ReadMe.
